# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Concurrency
email: jherrlin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  BS CS student at LNU, Vaxjo, Sweden
baseurl: "/Concurrency" # the subpath of your site, e.g. /blog
url: "http://jherrlin.github.io/Concurrency/" # the base hostname & protocol for your site
twitter_username: jherrlin
github_username:  jherrlin

# Build settings
markdown: kramdown
